version: "3.1"

services:
  db:
    image: mysql
    container_name: db
    networks:
      - go_todo
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: go_todo
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: "Asia/Tokyo"
    volumes:
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3306:3306

  app:
    build: .
    volumes:
      - ./app:/app
    ports:
      - "8080:8080"
    networks:
      - go_todo
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_USER=user
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=go_todo
    tty: true

volumes:
  db:

networks:
  go_todo:
    name: go_todo
    driver: bridge
